@extends('layouts.app')
@section('title', $purchase->exists ? 'Editar compra' : 'Nueva compra')
@section('heading', 'Compras')
@section('content')
<div class="page-heading"><div><a class="back-link" href="{{ route('purchases.index') }}">← Volver a compras</a><h1>{{ $purchase->exists ? 'Editar borrador' : 'Nueva compra' }}</h1><p>Guarda primero el documento; confirmar afectará inventario.</p></div></div>
<form method="POST" action="{{ $purchase->exists ? route('purchases.update',$purchase->ulid) : route('purchases.store') }}" class="space-y-6">@csrf @if($purchase->exists)@method('PUT')@endif
<section class="card p-5 sm:p-7"><h2 class="card-title">Datos del documento</h2><div class="form-grid mt-5"><div><label class="label">Proveedor</label><input class="input" name="supplier_name" value="{{ old('supplier_name',$purchase->supplier_name) }}"></div><div><label class="label">Documento</label><input class="input" name="document_number" value="{{ old('document_number',$purchase->document_number) }}" placeholder="Factura, recibo…"></div><div><label class="label">Fecha y hora</label><input class="input" type="datetime-local" name="purchased_at" value="{{ old('purchased_at',$purchase->purchased_at?->setTimezone(new DateTimeZone('America/La_Paz'))->format('Y-m-d\TH:i')) }}" required></div><div class="sm:col-span-2"><label class="label">Notas</label><textarea class="input min-h-20" name="notes">{{ old('notes',$purchase->notes) }}</textarea></div></div></section>
<section class="card p-5 sm:p-7"><div class="flex items-center justify-between"><div><h2 class="card-title">Artículos</h2><p class="card-subtitle">El costo unitario corresponde a la unidad elegida.</p></div><button type="button" class="btn-secondary" data-add-row="purchase">+ Agregar artículo</button></div>
@php($purchaseRows=old('items',$purchase->exists ? $purchase->items->map(fn($i)=>['inventory_item_id'=>$i->inventory_item_id,'quantity'=>$i->quantity,'input_unit_id'=>$i->input_unit_id,'unit_cost'=>$i->unit_cost,'expires_at'=>$i->expires_at?->format('Y-m-d'),'no_expiration'=>$i->expires_at===null])->all() : [['inventory_item_id'=>'','quantity'=>'','input_unit_id'=>'','unit_cost'=>'','expires_at'=>'','no_expiration'=>true]]))
<div class="mt-5 space-y-3" data-rows="purchase">@foreach($purchaseRows as $index=>$row)@include('purchases.item-row',['index'=>$index,'row'=>$row])@endforeach</div></section>
<div class="flex justify-end gap-3"><a class="btn-secondary" href="{{ route('purchases.index') }}">Cancelar</a><button class="btn-primary">Guardar borrador</button></div></form>
<template id="purchase-template">@include('purchases.item-row',['index'=>'__INDEX__','row'=>['inventory_item_id'=>'','quantity'=>'','input_unit_id'=>'','unit_cost'=>'','expires_at'=>'','no_expiration'=>true]])</template>
@endsection
