@extends('layouts.app')
@section('title', 'Detalle de compra')
@section('heading', 'Compras')
@section('content')
<div class="page-heading"><div><a class="back-link" href="{{ route('purchases.index') }}">← Volver a compras</a><div class="mt-2 flex items-center gap-3"><h1>Compra {{ $purchase->document_number ?: '#'.$purchase->ulid }}</h1><span class="badge {{ $purchase->status===\App\Enums\PurchaseStatus::Posted ? 'badge-success' : ($purchase->status===\App\Enums\PurchaseStatus::Reversed ? 'badge-danger' : '') }}">{{ \App\Support\UiFormatter::purchaseStatus($purchase->status) }}</span></div><p>{{ $purchase->supplier_name ?: 'Sin proveedor' }} · {{ \App\Support\UiFormatter::date($purchase->purchased_at,true) }}</p></div>@if($purchase->status===\App\Enums\PurchaseStatus::Draft)@can('update',$purchase)<a class="btn-secondary" href="{{ route('purchases.edit',$purchase->ulid) }}">Editar borrador</a>@endcan@endif</div>
<section class="grid gap-4 sm:grid-cols-3"><div class="metric-card"><p class="metric-label">Total</p><p class="metric-value">{{ \App\Support\UiFormatter::money($total) }}</p></div><div class="metric-card"><p class="metric-label">Sucursal</p><p class="mt-3 text-xl font-semibold">{{ $purchase->branch->name }}</p></div><div class="metric-card"><p class="metric-label">Registrada por</p><p class="mt-3 text-xl font-semibold">{{ $purchase->createdBy?->name ?: 'Sistema' }}</p></div></section>
<section class="card mt-6"><div class="card-header"><div><h2 class="card-title">Detalle de artículos</h2><p class="card-subtitle">Cantidades, costos y caducidad</p></div></div><div class="table-wrap"><table><thead><tr><th>Artículo</th><th>Cantidad comprada</th><th>Equivalencia interna</th><th>Caducidad</th><th>Costo unitario</th><th>Total</th></tr></thead><tbody>@foreach($purchase->items as $item)<tr><td class="font-medium">{{ $item->inventoryItem->name }}</td><td>{{ \App\Support\UiFormatter::quantity($item->quantity,$item->inputUnit->symbol) }}</td><td>{{ \App\Support\UiFormatter::quantity($item->base_quantity,$item->inventoryItem->unit->symbol) }}</td><td>{{ $item->expires_at ? \App\Support\UiFormatter::date($item->expires_at) : 'Sin caducidad' }}</td><td>{{ \App\Support\UiFormatter::money($item->unit_cost) }}</td><td class="font-semibold">{{ \App\Support\UiFormatter::money($item->total_cost) }}</td></tr>@endforeach</tbody></table></div>@if($purchase->notes)<div class="border-t border-stone-100 p-5"><p class="text-xs font-semibold uppercase text-stone-400">Notas</p><p class="mt-2 text-sm">{{ $purchase->notes }}</p></div>@endif</section>
@can('update',$purchase)<div class="mt-6 flex justify-end">@if($purchase->status===\App\Enums\PurchaseStatus::Draft)<form method="POST" action="{{ route('purchases.post',$purchase->ulid) }}" onsubmit="return confirm('¿Confirmar esta compra? Se actualizará el inventario y ya no podrá editarse libremente.')">@csrf<button class="btn-primary">Confirmar compra</button></form>@elseif($purchase->status===\App\Enums\PurchaseStatus::Posted)<form method="POST" action="{{ route('purchases.reverse',$purchase->ulid) }}" class="flex flex-col gap-2 rounded-2xl border border-red-200 bg-red-50 p-4 sm:flex-row sm:items-end" onsubmit="return confirm('¿Revertir esta compra? Se crearán movimientos compensatorios.')">@csrf<div><label class="label" for="reason">Motivo de reversión</label><input class="input min-w-72" id="reason" name="reason" required></div><button class="btn-danger">Revertir compra</button></form>@endif</div>@endcan
@endsection
