@extends('layouts.app')
@section('title','Mesas')
@section('heading','Mesas')
@section('content')
<div class="page-heading"><div><h1>Mesas</h1><p>Situación y configuración de la sucursal. El estado se deriva de la cuenta activa.</p></div><div class="flex gap-2"><a class="btn-secondary" href="{{ route('sales.create') }}">Nueva venta</a>@can('create',\App\Models\RestaurantTable::class)<a class="btn-primary" href="{{ route('tables.create') }}">+ Nueva mesa</a>@endcan</div></div>
<div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
@forelse($tables as $table)@php($hasReady=$table->openOrder?->items->contains('status',\App\Enums\OrderItemStatus::Ready) ?? false)<article class="card p-5 {{ $table->is_active ? '' : 'opacity-60' }}"><div class="flex items-start justify-between"><div><p class="text-xl font-semibold">{{ $table->name }}</p><p class="mt-1 text-xs text-stone-500">{{ $table->capacity ? $table->capacity.' personas' : 'Capacidad no configurada' }}</p></div><span class="badge {{ ! $table->is_active ? '' : ($hasReady ? 'badge-danger' : ($table->openOrder ? 'bg-amber-100 text-amber-800' : 'badge-success')) }}">{{ ! $table->is_active ? 'Inactiva' : ($hasReady ? 'Atención' : ($table->openOrder ? 'Ocupada' : 'Libre')) }}</span></div>
@if($table->openOrder)<div class="mt-5 rounded-xl bg-stone-50 p-4"><p class="font-semibold">{{ $table->openOrder->formattedNumber() }}</p><p class="mt-1 text-lg font-semibold text-orange-700">{{ \App\Support\UiFormatter::money($table->openOrder->total) }}</p><p class="mt-1 text-xs text-stone-500">{{ (int) $table->openOrder->opened_at->diffInMinutes(now()) }} min</p>@if($hasReady)<p class="mt-2 text-sm font-semibold text-red-700">⚠ Tiene productos listos</p>@endif</div><a class="btn-primary mt-4 w-full" href="{{ route('orders.show',$table->openOrder->ulid) }}">Continuar pedido</a>
@elseif($table->is_active) @can('create',\App\Models\Order::class)<form method="POST" action="{{ route('tables.open',$table->ulid) }}" class="mt-6 space-y-3">@csrf<fieldset><legend class="label">&iquest;C&oacute;mo cobrar&aacute; esta mesa?</legend><div class="mt-2 grid gap-2">@foreach(\App\Enums\TableChargeMode::cases() as $mode)<label class="flex cursor-pointer items-center gap-2 rounded-xl border border-stone-200 p-3"><input type="radio" name="charge_mode" value="{{ $mode->value }}" required><span>{{ $mode->label() }}</span></label>@endforeach</div></fieldset><label class="block"><span class="label">Cliente (opcional)</span><input class="input" name="customer_name" maxlength="255"></label><button class="btn-primary w-full">Abrir mesa</button></form>@endcan @endif @can('update',$table)<a class="btn-secondary mt-3 w-full" href="{{ route('tables.edit',$table->ulid) }}">Configurar</a>@endcan</article>
@empty<div class="empty-state card sm:col-span-2"><p>No hay mesas configuradas para esta sucursal.</p>@can('create',\App\Models\RestaurantTable::class)<a class="btn-primary mt-3 inline-flex" href="{{ route('tables.create') }}">Crear primera mesa</a>@else<p class="mt-2 text-sm">Solicita a un administrador que configure las mesas.</p>@endcan</div>@endforelse
</div>
@endsection
