@extends('layouts.app')
@section('title', 'Reportes')
@section('heading', 'Reportes')
@section('content')
@php
    $tabs = [
        'summary' => ['Resumen','reports.index',true], 'sales' => ['Ventas','reports.sales',false], 'products' => ['Productos','reports.products',false], 'cash' => ['Caja','reports.cash',false],
        'expenses' => ['Gastos','reports.expenses',true], 'purchases' => ['Compras','reports.purchases',true], 'inventory' => ['Inventario','reports.inventory',true], 'waste' => ['Mermas','reports.waste',true], 'profitability' => ['Rentabilidad','reports.profitability',true],
    ];
    $exportReport = ['sales'=>'sales','cash'=>'cash','expenses'=>'expenses','purchases'=>'purchases','inventory'=>'inventory'][$section] ?? null;
@endphp
<div class="page-heading">
    <div><h1>Análisis operativo y financiero</h1><p>{{ $range->label }} · {{ $range->from->format('d/m/Y') }}–{{ $range->to->format('d/m/Y') }} · datos de {{ request()->attributes->get('branch')->name }}</p></div>
    @if($exportReport)
        @can('reports.export')
            <a class="btn-secondary" href="{{ route('reports.export', array_merge([$exportReport], request()->query())) }}">Exportar CSV</a>
        @endcan
    @endif
</div>
<nav class="mb-6 flex gap-2 overflow-x-auto pb-2" aria-label="Secciones de reportes">@foreach($tabs as $key=>$tab)@if(!$tab[2] || auth()->user()->can('reports.financial'))<a class="{{ $section===$key ? 'btn-primary':'btn-secondary' }} whitespace-nowrap" href="{{ route($tab[1],$range->query()) }}">{{ $tab[0] }}</a>@endif @endforeach</nav>
<form class="card mb-6 grid gap-3 p-4 sm:grid-cols-3 xl:grid-cols-7" method="GET">
    <select class="input" name="preset"><option value="today" @selected($range->preset==='today')>Hoy</option><option value="yesterday" @selected($range->preset==='yesterday')>Ayer</option><option value="week" @selected($range->preset==='week')>Esta semana</option><option value="month" @selected($range->preset==='month')>Este mes</option><option value="previous_month" @selected($range->preset==='previous_month')>Mes anterior</option><option value="custom" @selected($range->preset==='custom')>Personalizado</option></select>
    <input class="input" type="date" name="date_from" value="{{ $range->from->toDateString() }}" aria-label="Desde"><input class="input" type="date" name="date_to" value="{{ $range->to->toDateString() }}" aria-label="Hasta">
    @if(in_array($section,['sales','products']))<select class="input" name="payment_method"><option value="">Todos los pagos</option>@foreach(\App\Enums\PaymentMethod::cases() as $method)<option value="{{ $method->value }}" @selected(($filters['payment_method']??null)===$method->value)>{{ \App\Support\UiFormatter::paymentMethod($method) }}</option>@endforeach</select><select class="input" name="category_id"><option value="">Todas las categorías</option>@foreach($productCategories as $category)<option value="{{ $category->id }}" @selected(($filters['category_id']??null)===$category->id)>{{ $category->name }}</option>@endforeach</select><select class="input" name="product_id"><option value="">Todos los productos</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected(($filters['product_id']??null)===$product->id)>{{ $product->name }}</option>@endforeach</select><select class="input" name="variant_id"><option value="">Todas las variantes</option>@foreach($variants as $variant)<option value="{{ $variant->id }}" @selected(($filters['variant_id']??null)===$variant->id)>{{ $variant->product->name }} · {{ $variant->name }}</option>@endforeach</select>@endif
    @if($section==='expenses')<select class="input" name="expense_category_id"><option value="">Todas las categorías</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(($filters['expense_category_id']??null)===$category->id)>{{ $category->name }}</option>@endforeach</select><select class="input" name="expense_method"><option value="">Todos los métodos</option>@foreach(\App\Enums\ExpensePaymentMethod::cases() as $method)<option value="{{ $method->value }}" @selected(($filters['expense_method']??null)===$method->value)>{{ \App\Support\UiFormatter::expensePayment($method) }}</option>@endforeach</select>@endif
    @if($section==='inventory')<select class="input" name="sort"><option value="name">Nombre</option><option value="value" @selected(($filters['sort']??null)==='value')>Mayor valor</option><option value="low_stock" @selected(($filters['sort']??null)==='low_stock')>Stock bajo</option><option value="expiration" @selected(($filters['sort']??null)==='expiration')>Vencimiento</option></select>@endif
    <button class="btn-primary">Aplicar filtros</button>
</form>

@if($section==='summary')
<section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
    @foreach([['Ventas',$sales['sales_total']],['Pedidos cobrados',$sales['orders_paid']],['Ticket promedio',$sales['average_ticket']],['Efectivo',$sales['payments']->firstWhere('method','cash')['amount'] ?? '0.00'],['QR',$sales['payments']->firstWhere('method','qr')['amount'] ?? '0.00'],['Gastos',$expenses['total']],['Compras inventario',$purchases['total']],['Mermas estimadas',$waste['total_cost']],['Resultado estimado',$profitability['estimated_result']],['Inventario actual',$inventory['total_value']]] as $metric)<div class="metric-card"><p class="metric-label">{{ $metric[0] }}</p><p class="metric-value">{{ is_int($metric[1]) ? $metric[1] : \App\Support\UiFormatter::money($metric[1]) }}</p></div>@endforeach
</section>
<div class="mt-6 grid gap-6 xl:grid-cols-2"><section class="card"><div class="card-header"><h2 class="card-title">Ventas por día</h2></div><div class="table-wrap"><table><thead><tr><th>Día</th><th>Pedidos</th><th>Ventas</th></tr></thead><tbody>@forelse($sales['by_day'] as $row)<tr><td>{{ $row['label'] }}</td><td>{{ $row['orders'] }}</td><td><span>{{ \App\Support\UiFormatter::money($row['amount']) }}</span><progress class="ml-3 h-2 max-w-32" max="{{ $sales['sales_total'] === '0.00' ? '1.00' : $sales['sales_total'] }}" value="{{ $row['amount'] }}">{{ $row['amount'] }}</progress></td></tr>@empty<tr><td colspan="3"><div class="empty-state">Sin ventas cobradas.</div></td></tr>@endforelse</tbody></table></div></section><section class="card"><div class="card-header"><div><h2 class="card-title">Actividad por usuario</h2><p class="card-subtitle">Conteos operativos, no evaluación de desempeño.</p></div></div><div class="table-wrap"><table><thead><tr><th>Usuario</th><th>Pedidos</th><th>Pagos</th><th>Cajas</th><th>Gastos</th></tr></thead><tbody>@foreach($users as $row)<tr><td>{{ $row['name'] }}</td><td>{{ $row['orders'] }}</td><td>{{ $row['payments'] }}</td><td>{{ $row['cash_sessions'] }}</td><td>{{ $row['expenses'] }}</td></tr>@endforeach</tbody></table></div></section></div>
@elseif($section==='sales')
<section class="grid gap-4 sm:grid-cols-3"><div class="metric-card"><p class="metric-label">Ventas cobradas</p><p class="metric-value">{{ \App\Support\UiFormatter::money($sales['sales_total']) }}</p></div><div class="metric-card"><p class="metric-label">Pedidos</p><p class="metric-value">{{ $sales['orders_paid'] }}</p></div><div class="metric-card"><p class="metric-label">Ticket promedio</p><p class="metric-value">{{ \App\Support\UiFormatter::money($sales['average_ticket']) }}</p></div></section>
<div class="mt-6 grid gap-6 xl:grid-cols-2">@foreach([['Métodos de pago',$sales['payments'],'method'],['Ventas por hora',$sales['by_hour'],'label'],['Tipo de pedido',$sales['by_type'],'name'],['Categorías',$sales['by_category'],'name']] as $block)<section class="card"><div class="card-header"><h2 class="card-title">{{ $block[0] }}</h2></div><div class="table-wrap"><table><tbody>@foreach($block[1] as $row)<tr><td>{{ $row[$block[2]] }}</td><td>{{ isset($row['percentage']) ? $row['percentage'].'%' : ($row['orders']??$row['count']) }}@if(isset($row['percentage']))<progress class="ml-2 h-2 max-w-24" max="100" value="{{ $row['percentage'] }}">{{ $row['percentage'] }}%</progress>@endif</td><td>{{ \App\Support\UiFormatter::money($row['amount']) }}</td></tr>@endforeach</tbody></table></div></section>@endforeach</div>
@elseif($section==='products')
<div class="grid gap-6 xl:grid-cols-2">@foreach([['Productos más vendidos',$sales['products']],['Variantes / tamaños',$sales['variants']]] as $block)<section class="card"><div class="card-header"><h2 class="card-title">{{ $block[0] }}</h2></div><div class="table-wrap"><table><thead><tr><th>Nombre</th><th>Unidades</th><th>Ingreso</th></tr></thead><tbody>@foreach($block[1] as $row)<tr><td>{{ $row['name'] }}</td><td>{{ $row['quantity'] }}<progress class="ml-2 h-2 max-w-24" max="{{ $block[1]->first()['quantity'] ?? '1.000' }}" value="{{ $row['quantity'] }}">{{ $row['quantity'] }}</progress></td><td>{{ \App\Support\UiFormatter::money($row['revenue']) }}</td></tr>@endforeach</tbody></table></div></section>@endforeach</div>
<div class="mt-6 grid gap-6 xl:grid-cols-2"><section class="card"><div class="card-header"><div><h2 class="card-title">Sabores solicitados</h2><p class="card-subtitle">Participación proporcional por fracción; cada pizza completa conserva una sola unidad vendida.</p></div></div><div class="table-wrap"><table><tbody>@foreach($sales['pizza_analysis']['flavors'] as $row)<tr><td>{{ $row['name'] }}</td><td>{{ $row['quantity'] }}</td></tr>@endforeach</tbody></table></div></section><section class="card"><div class="card-header"><h2 class="card-title">Combinaciones frecuentes</h2></div><div class="table-wrap"><table><tbody>@foreach($sales['pizza_analysis']['combinations'] as $row)<tr><td>{{ $row['name'] }}</td><td>{{ $row['quantity'] }}</td></tr>@endforeach</tbody></table></div></section></div>
<div class="mt-6 grid gap-6 xl:grid-cols-3"><section class="card"><div class="card-header"><h2 class="card-title">Secciones configuradas</h2></div><div class="table-wrap"><table><tbody>@foreach($sales['pizza_analysis']['section_counts'] as $row)<tr><td>{{ $row['sections'] }} sección(es)</td><td>{{ $row['quantity'] }}</td></tr>@endforeach</tbody></table></div></section>@foreach([['Extras solicitados',$sales['pizza_analysis']['extras']],['Ingredientes retirados',$sales['pizza_analysis']['removed']]] as $block)<section class="card"><div class="card-header"><h2 class="card-title">{{ $block[0] }}</h2></div><div class="table-wrap"><table><tbody>@forelse($block[1] as $row)<tr><td>{{ $row['name'] }}</td><td>{{ $row['count'] }}</td></tr>@empty<tr><td><div class="empty-state">Sin datos.</div></td></tr>@endforelse</tbody></table></div></section>@endforeach</div>
@elseif($section==='cash')
<div class="card"><div class="table-wrap"><table><thead><tr><th>Caja</th><th>Apertura</th><th>Cierre</th><th>Usuario</th><th>Esperado</th><th>Contado</th><th>Diferencia</th><th>Duración</th><th></th></tr></thead><tbody>@forelse($sessions as $session)<tr><td>{{ $session->cashRegister->name }}</td><td>{{ \App\Support\UiFormatter::date($session->opened_at,true) }}</td><td>{{ \App\Support\UiFormatter::date($session->closed_at,true) }}</td><td>{{ $session->openedBy->name }}</td><td>{{ \App\Support\UiFormatter::money($session->status===\App\Enums\CashSessionStatus::Closed ? $session->expected_cash_amount : $session->report_summary['expected_cash']) }}</td><td>{{ $session->counted_cash_amount ? \App\Support\UiFormatter::money($session->counted_cash_amount) : '—' }}</td><td class="{{ ($session->difference_amount??0)!=0 ? 'text-red-700 font-semibold':'' }}">{{ $session->difference_amount!==null ? \App\Support\UiFormatter::money($session->difference_amount) : '—' }}</td><td>{{ $session->duration_minutes }} min</td><td><a class="link" href="{{ route('reports.cash.show',$session->ulid) }}">Detalle</a></td></tr>@empty<tr><td colspan="9"><div class="empty-state">Sin sesiones en el rango.</div></td></tr>@endforelse</tbody></table></div>{{ $sessions->links() }}</div>
@elseif($section==='expenses')
<section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div class="metric-card"><p class="metric-label">Gastos activos</p><p class="metric-value">{{ \App\Support\UiFormatter::money($expenses['total']) }}</p></div>@foreach($expenses['by_method']->take(3) as $row)<div class="metric-card"><p class="metric-label">{{ $row['name'] }}</p><p class="metric-value">{{ \App\Support\UiFormatter::money($row['amount']) }}</p></div>@endforeach</section>
<div class="mt-6 grid gap-6 xl:grid-cols-3">@foreach([['Por categoría',$expenses['by_category']],['Por documento',$expenses['by_document']],['Por proveedor',$expenses['by_supplier']],['Por día',$expenses['by_day']],['Por mes',$expenses['by_month']]] as $block)<section class="card"><div class="card-header"><h2 class="card-title">{{ $block[0] }}</h2></div><div class="table-wrap"><table><tbody>@foreach($block[1] as $row)<tr><td>{{ $row['name'] }}</td><td>{{ \App\Support\UiFormatter::money($row['amount']) }}</td></tr>@endforeach</tbody></table></div></section>@endforeach</div>
<div class="card mt-6"><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Descripción</th><th>Categoría</th><th>Proveedor</th><th>Documento</th><th>Método</th><th>Monto</th></tr></thead><tbody>@foreach($expenseRows as $expense)<tr><td>{{ \App\Support\UiFormatter::date($expense->expense_date) }}</td><td>{{ $expense->description }}</td><td>{{ $expense->category->name }}</td><td>{{ $expense->supplier?->name??'—' }}</td><td>{{ \App\Support\UiFormatter::expenseDocument($expense->document_type) }}</td><td>{{ \App\Support\UiFormatter::expensePayment($expense->payment_method) }}</td><td>{{ \App\Support\UiFormatter::money($expense->amount) }}</td></tr>@endforeach</tbody></table></div>{{ $expenseRows->links() }}</div>
@elseif($section==='purchases')
<section class="grid gap-4 sm:grid-cols-2"><div class="metric-card"><p class="metric-label">Compras confirmadas</p><p class="metric-value">{{ \App\Support\UiFormatter::money($purchases['total']) }}</p></div><div class="metric-card"><p class="metric-label">Documentos</p><p class="metric-value">{{ $purchases['purchases'] }}</p></div></section><div class="mt-6 grid gap-6 xl:grid-cols-2"><section class="card"><div class="card-header"><h2 class="card-title">Artículos comprados</h2></div><div class="table-wrap"><table><thead><tr><th>Artículo</th><th>Cantidad</th><th>Costo promedio</th><th>Total</th></tr></thead><tbody>@foreach($purchases['items'] as $row)<tr><td>{{ $row['name'] }}</td><td>{{ $row['quantity'] }} {{ $row['unit'] }}</td><td>{{ \App\Support\UiFormatter::money($row['average_cost']) }}</td><td>{{ \App\Support\UiFormatter::money($row['amount']) }}</td></tr>@endforeach</tbody></table></div></section><section class="card"><div class="card-header"><h2 class="card-title">Proveedores</h2></div><div class="table-wrap"><table><tbody>@foreach($purchases['by_supplier'] as $row)<tr><td>{{ $row['name'] }}</td><td>{{ \App\Support\UiFormatter::money($row['amount']) }}</td></tr>@endforeach</tbody></table></div></section></div>
@elseif($section==='inventory')
<div class="metric-card mb-6"><p class="metric-label">Valor actual del inventario</p><p class="metric-value">{{ \App\Support\UiFormatter::money($inventory['total_value']) }}</p></div><div class="card"><div class="table-wrap"><table><thead><tr><th>Artículo</th><th>Físico</th><th>Vencido</th><th>Reservado</th><th>Disponible</th><th>Mínimo</th><th>Costo promedio</th><th>Valor</th><th>Próximo vencimiento</th></tr></thead><tbody>@foreach($inventory['items'] as $item)<tr><td>{{ $item->name }}</td><td>{{ \App\Support\UiFormatter::quantity($item->physical_quantity,$item->unit->symbol) }}</td><td>{{ \App\Support\UiFormatter::quantity($item->expired_quantity,$item->unit->symbol) }}</td><td>{{ \App\Support\UiFormatter::quantity($item->reserved_quantity,$item->unit->symbol) }}</td><td>{{ \App\Support\UiFormatter::quantity($item->available_quantity,$item->unit->symbol) }}</td><td>{{ \App\Support\UiFormatter::quantity($item->inventoryStocks->first()?->minimum_quantity??'0',$item->unit->symbol) }}</td><td>{{ \App\Support\UiFormatter::money($item->display_average_cost) }}</td><td>{{ \App\Support\UiFormatter::money($item->display_value) }}</td><td>{{ \App\Support\UiFormatter::date($item->next_expiration_at) }}</td></tr>@endforeach</tbody></table></div></div><section class="card mt-6"><div class="card-header"><div><h2 class="card-title">Consumo real del periodo</h2><p class="card-subtitle">Derivado del ledger, no de recetas actuales.</p></div></div><div class="table-wrap"><table><tbody>@foreach($consumption['by_item'] as $row)<tr><td>{{ $row['name'] }}</td><td>{{ $row['quantity'] }} {{ $row['unit'] }}</td><td>{{ \App\Support\UiFormatter::money($row['cost']) }}</td></tr>@endforeach</tbody></table></div></section>
@elseif($section==='waste')
<div class="metric-card mb-6"><p class="metric-label">Costo estimado de merma</p><p class="metric-value">{{ \App\Support\UiFormatter::money($waste['total_cost']) }}</p><p class="metric-help">Basado en el costo registrado en el movimiento; no es contabilidad formal.</p></div><div class="card"><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Artículo</th><th>Cantidad</th><th>Costo estimado</th><th>Motivo</th><th>Usuario</th><th>Lote</th></tr></thead><tbody>@foreach($waste['movements'] as $movement)<tr><td>{{ \App\Support\UiFormatter::date($movement->occurred_at,true) }}</td><td>{{ $movement->inventoryItem->name }}</td><td>{{ \App\Support\UiFormatter::quantity($movement->quantity,$movement->inventoryItem->unit->symbol) }}</td><td>{{ \App\Support\UiFormatter::money($movement->total_cost) }}</td><td>{{ $movement->reason }}</td><td>{{ $movement->createdBy?->name }}</td><td>{{ $movement->inventoryBatch?->ulid??'—' }}</td></tr>@endforeach</tbody></table></div></div>
@elseif($section==='profitability')
<section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">@foreach([['Ventas',$profitability['sales']],['Producción estimada',$profitability['production_cost']],['Gastos',$profitability['expenses']],['Mermas estimadas',$profitability['waste_cost']],['Resultado estimado',$profitability['estimated_result']]] as $metric)<div class="metric-card"><p class="metric-label">{{ $metric[0] }}</p><p class="metric-value">{{ \App\Support\UiFormatter::money($metric[1]) }}</p></div>@endforeach</section><div class="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Metodología estimada:</strong> {{ $profitability['methodology'] }}</div><div class="card mt-6"><div class="table-wrap"><table><thead><tr><th>Variante</th><th>Ingreso histórico</th><th>Costo histórico/estimado</th><th>Margen estimado</th></tr></thead><tbody>@foreach($profitability['by_variant'] as $row)<tr><td>{{ $row['name'] }}</td><td>{{ \App\Support\UiFormatter::money($row['revenue']) }}</td><td>{{ \App\Support\UiFormatter::money($row['estimated_cost']) }}</td><td>{{ \App\Support\UiFormatter::money($row['estimated_margin']) }}</td></tr>@endforeach</tbody></table></div></div>
@endif
@endsection
