@extends('layouts.app')
@section('title', 'Cocina')
@section('heading', 'Cocina')
@section('content')
<div class="page-heading"><div><h1>Cocina</h1><p>Solo productos que requieren preparación. Sin precios ni información financiera.</p></div><a class="btn-secondary" href="{{ route('kitchen.index') }}">Actualizar</a></div>
@php($columns = [[\App\Enums\OrderItemStatus::Sent, 'Nuevos'], [\App\Enums\OrderItemStatus::Preparing, 'Preparando'], [\App\Enums\OrderItemStatus::Ready, 'Listos']])
<div class="grid gap-5 xl:grid-cols-3">
@foreach($columns as [$status, $label])
<section><div class="mb-3 flex items-center justify-between"><h2 class="text-lg font-semibold uppercase tracking-wide">{{ $label }}</h2></div><div class="space-y-4">
@forelse($dispatches as $dispatch)@php($visible=$dispatch->items->filter(fn($link) => $link->orderItem->status === $status && $link->orderItem->requires_preparation))@if($visible->isNotEmpty())<article class="card border-l-4 border-l-orange-500 p-5"><p class="font-semibold">{{ $dispatch->order->formattedOperationalNumber() }} · {{ $dispatch->order->restaurantTable?->name ?? 'Para llevar' }}</p><p class="text-xs text-stone-500">Tanda #{{ $dispatch->sequence_number }} · {{ \App\Support\UiFormatter::date($dispatch->dispatched_at,true) }} · {{ $dispatch->dispatched_at->diffForHumans(short:true) }}</p><div class="mt-4 space-y-4">@foreach($visible as $link)@php($item=$link->orderItem)<div class="rounded-xl bg-stone-50 p-4"><p class="text-lg font-semibold">{{ \App\Support\UiFormatter::quantity($item->quantity) }} × {{ $item->sections->isNotEmpty() ? strtoupper(\App\Support\UiFormatter::variantName($item->sections->first()->variant_name_snapshot, $item->configuration_snapshot['size_key'] ?? null)) : $item->productVariant->product->name.' '.\App\Support\UiFormatter::variantName($item->productVariant->name, $item->productVariant->size_key) }}</p>@if($item->sections->isNotEmpty())<div class="mt-2">@foreach($item->sections as $section)<p class="font-semibold">{{ $section->fractionLabel() }} {{ $section->product_name_snapshot }}</p>@foreach($item->modifiers->where('order_item_section_id',$section->id) as $modifier)<p class="pl-4 text-sm font-semibold">{{ $modifier->type===\App\Enums\ModifierOptionType::Add ? '+' : '-' }} {{ strtoupper($modifier->name_snapshot) }}</p>@endforeach @endforeach @foreach($item->modifiers->whereNull('order_item_section_id') as $modifier)<p class="text-sm font-semibold">{{ $modifier->type===\App\Enums\ModifierOptionType::Add ? '+' : '-' }} {{ strtoupper($modifier->name_snapshot) }}</p>@endforeach</div>@endif @if($item->notes)<p class="mt-2 font-semibold uppercase text-red-700">{{ $item->notes }}</p>@endif @if($item->fulfillment_type===\App\Enums\OrderType::Takeaway)<p class="mt-2 text-sm font-semibold text-orange-700">PARA LLEVAR</p>@endif @can('update',$dispatch)@if($status!==\App\Enums\OrderItemStatus::Ready)<form class="mt-3" method="POST" action="{{ $status===\App\Enums\OrderItemStatus::Sent ? route('kitchen.items.start',$item->ulid) : route('kitchen.items.ready',$item->ulid) }}">@csrf<button class="btn-primary w-full">{{ $status===\App\Enums\OrderItemStatus::Sent ? 'COMENZAR' : 'MARCAR LISTO' }}</button></form>@endif @endcan</div>@endforeach</div></article>@endif @empty<div class="empty-state card">Sin productos.</div>@endforelse
</div></section>
@endforeach
</div>
@endsection
